model_path = {
    "Qwen2.5_1.5B_Instruct": "../../small_model/Qwen2.5_1.5B_Instruct",
    "Qwen2___5-7B-Instruct": "../../large_model/Qwen2.5-7B-Instruct/Qwen/Qwen2___5-7B-Instruct",
    "Qwen2___5-14B-Instruct": "../../large_model/Qwen2.5-14B-Instruct/Qwen/Qwen2___5-14B-Instruct",
    "Qwen2___5-32B-Instruct": "../../large_model/Qwen2.5-32B-Instruct/Qwen/Qwen2___5-32B-Instruct",
    "Qwen2___5-72B-Instruct": "../../large_model/Qwen2.5-72B-Instruct/Qwen/Qwen2___5-72B-Instruct",
    "internlm2_5-1_8b-chat": "../../small_model/internlm2_5-1_8b-chat/Shanghai_AI_Laboratory/internlm2_5-1_8b-chat",
    "Llama-3___2-1B-Instruct": "../../small_model/Llama-3.2-1B-Instruct/LLM-Research/Llama-3___2-1B-Instruct",
    "MiniCPM-2B-dpo-bf16": "../../small_model/MiniCPM2B/OpenBMB/MiniCPM-2B-dpo-bf16",
    "Phi-3___5-mini-instruct": "../../small_model/Phi-3.5-mini-instruct/LLM-Research/Phi-3___5-mini-instruct",
    "DeepSeek-R1-Distill-Qwen-7B": "../../large_model/DeepSeek-R1-Distill-Qwen-7B/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
    "DeepSeek-R1-Distill-Qwen-14B": "../../large_model/DeepSeek-R1-Distill-Qwen-14B/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    "DeepSeek-R1-Distill-Qwen-32B": "../../large_model/DeepSeek-R1-Distill-Qwen-32B/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
    "Yi-1___5-6B-Chat": "../../large_model/Yi-1.5-6B-Chat/01ai/Yi-1___5-6B-Chat",
    "Yi-1___5-9B-Chat": "../../large_model/Yi-1.5-9B-Chat/01ai/Yi-1___5-9B-Chat",
    "Yi-1___5-34B-Chat": "../../large_model/Yi-1.5-34B-Chat/01ai/Yi-1___5-34B-Chat",
    "Yuan2___0-51B-hf": "../../large_model/Yuan2.0-51B-hf/IEITYuan/Yuan2___0-51B-hf",
    "internlm2_5-7b": "../../large_model/internlm2_5-7b/Shanghai_AI_Laboratory/internlm2_5-7b",
    "internlm2_5-20b": "../../large_model/internlm2_5-20b/Shanghai_AI_Laboratory/internlm2_5-20b",
    "Llama-3___3-70B-Instruct": "../../large_model/Llama-3.3-70B-Instruct/LLM-Research/Llama-3___3-70B-Instruct",
    "Meta-Llama-3-8B-Instruct": "../../large_model/Meta-Llama-3-8B-Instruct/LLM-Research/Meta-Llama-3-8B-Instruct",
    "Meta-Llama-3___1-8B-Instruct": "../../large_model/Meta-Llama-3.1-8B-Instruct/LLM-Research/Meta-Llama-3___1-8B-Instruct",
    "Meta-Llama-3___1-70B-Instruct": "../../large_model/Meta-Llama-3.1-70B-Instruct/LLM-Research/Meta-Llama-3___1-70B-Instruct",
    "Qwen2___5-3B-Instruct": "../../small_model/Qwen2___5-3B-Instruct/Qwen/Qwen2___5-3B-Instruct",
    "QwQ-32B-Preview": "../../large_model/QwQ-32B-Preview/Qwen/QwQ-32B-Preview",
    "Mixtral-8x7B-Instruct-v0___1": "../..large_model/Mixtral-8x7B-Instruct-v0.1/AI-ModelScope/Mixtral-8x7B-Instruct-v0___1",
    "Phi-3___5-MoE-instruct": "../../large_model/Phi-3.5-MoE-instruct/LLM-Research/Phi-3___5-MoE-instruct",
    "phi-4": "../../large_model/phi-4/LLM-Research/phi-4"
}

model_gpu_use = {
    "internlm2_5-1_8b-chat": 1,
    "Qwen2.5_1.5B_Instruct": 1,
    "Llama-3___2-1B-Instruct": 1,
    "MiniCPM-2B-dpo-bf16": 1,
    "Phi-3___5-mini-instruct": 4,
    "Qwen2___5-3B-Instruct": 1,
     
    "Qwen2___5-7B-Instruct": 1,
    "Qwen2___5-14B-Instruct": 1,
    "Qwen2___5-32B-Instruct": 4,
    "Qwen2___5-72B-Instruct": 4,
    "DeepSeek-R1-Distill-Qwen-7B": 1,
    "DeepSeek-R1-Distill-Qwen-14B": 1,
    "DeepSeek-R1-Distill-Qwen-32B": 4,
    "Mixtral-8x7B-Instruct-v0___1": 4,
    "Phi-3___5-MoE-instruct": 4,
    "phi-4": 4,
    
    "Yi-1___5-6B-Chat": 1,
    "Yi-1___5-9B-Chat": 1,
    "Yi-1___5-34B-Chat": 4,
    "Yuan2___0-51B-hf": 4,
    "Llama-3___3-70B-Instruct": 4,
    "Meta-Llama-3-8B-Instruct": 1,
    "Meta-Llama-3___1-8B-Instruct": 1,
    "Meta-Llama-3___1-70B-Instruct": 4,
    "QwQ-32B-Preview": 4,
    "internlm2_5-7b": 2,
    "internlm2_5-20b": 4,
}